apiVersion: v1
data:
  init.sql: "-- Create database if not exists\r\nIF NOT EXISTS (SELECT * FROM sys.databases
    WHERE name = 'collateral_db')\r\nBEGIN\r\n    CREATE DATABASE collateral_db;\r\nEND\r\nGO\r\n\r\n--
    Use the database\r\nUSE collateral_db;\r\nGO\r\n\r\n-- Create table if not exists\r\nIF
    NOT EXISTS (SELECT * FROM sysobjects WHERE name='MyTable' AND xtype='U')\r\nBEGIN\r\n
    \   CREATE TABLE MyTable (\r\n        Id INT PRIMARY KEY IDENTITY(1,1),\r\n        Name
    NVARCHAR(100) NOT NULL\r\n    );\r\nEND\r\nGO"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"mssql-initdb","creationTimestamp":null},"data":{"init.sql":"-- Create database if not exists\r\nIF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'collateral_db')\r\nBEGIN\r\n    CREATE DATABASE collateral_db;\r\nEND\r\nGO\r\n\r\n-- Use the database\r\nUSE collateral_db;\r\nGO\r\n\r\n-- Create table if not exists\r\nIF NOT EXISTS (SELECT * FROM sysobjects WHERE name='MyTable' AND xtype='U')\r\nBEGIN\r\n    CREATE TABLE MyTable (\r\n        Id INT PRIMARY KEY IDENTITY(1,1),\r\n        Name NVARCHAR(100) NOT NULL\r\n    );\r\nEND\r\nGO"}}
  creationTimestamp: null
  name: mssql-initdb
